### PR TITLE
fix links

### PR DESCRIPTION
**Pull request by rened**
I think including `:doc:` fixes the links, but I dont know how to actually test this.

### CODE REVIEW

**Comment by pluskid** [comment]
Rened,


Thanks for all the recent prs. I'm currently in traveling, I will merge them as soon as I have more stable internet access.


- chiyuan

**Comment by rened** [comment]
No worries, enjoy your trip! :-)

**Comment by pluskid** [comment]
@rened Thanks! Yes, adding `doc` should fix them. If you have Sphinx installed locally, `make livehtml` in the docs directory could preview them locally. But I believe this fix is ready to merge.

However, I cannot merge this from the github web interface because there is conflict. Could you please rebase this to the latest master? Thanks again!

**Comment by rened** [comment]
Sorry, didn't see that - fixed.

**Pull request merged**
