### PR TITLE
Typo fixes and wording clarifications

### PR DESCRIPTION
**Pull request by slundberg**
This is a great intro to using Mocha. I noticed a few small issues while studying this document so I went ahead and addressed them. They should all be simple clarifications, but let me know if anything is incorrect.

### CODE REVIEW

**Comment by slundberg** [comment]
The second commit adds a short example about loading and using a network previously trained using Mocha.

**Comment by pluskid** [comment]
Thanks! This is great!

**Comment by JohnHBrock** [comment]
That second commit is especially helpful, thanks.

**Comment by slundberg** [comment]
Glad to hear it is helpful. I figured I might as well record the answers to the questions I ran into while learning Mocha.

**Pull request merged**
