### PR TITLE
Some updates for Julia v0.4.0-rc1

### PR DESCRIPTION
**Pull request by droidicus**
Here are some changes for Julia v0.4.0-rc1, checked on both v0.4 and v0.3, CPU and GPU.

One note, I have been getting sporadic test failures in GPU mode on one of the new layers. When it does happen (not every time), the error is occuring here:
```
ERROR: test failed: -eps < state.loss - expected_loss < eps
 in error at error.jl:21 (repeats 2 times)
while loading C:\Users\droidicus\.julia\v0.3\Mocha\test\layers/binary-cross-entropy-loss.jl, in expression starting on line 73
while loading C:\Users\droidicus\.julia\v0.3\Mocha\test\runtests.jl, in expression starting on line 84
```

I don't think this is due to these changes, but I wanted to point it out in case there is a subtle bug in this pull request.

### CODE REVIEW

**Comment by pluskid** [comment]
@droidicus Thanks!

For the test error, when getting the error, did you get print for `Float64` or `Float32`? Something like this:
```
Testing BinaryCrossEntropyLossLayer on GPU{Float32}
```
One possible reason for this kinds of test failure occurring randomly might be due to the numerical precision difference between GPU/CPU and float32 / float64. @benmoran Do you have time to check if you could reproduce this error on `BinaryCrossEntropyLossLayer` and make sure it is not a bug? In that case, we could probably increase `eps` to avoid this error (though the current `eps` for `Float32` is already quite large).

**Comment by droidicus** [comment]
Ah yes, that would be useful!
```
-- Testing BinaryCrossEntropyLossLayer on GPUBackend{Float64}...
    > [4,6,7,6,7]
```

**Comment by droidicus** [comment]
Here is the full output of the test script, with the error shown
```
-- Testing BinaryCrossEntropyLossLayer on CPUBackend{Float32}...
    > [3,4]
state.loss - expected_loss => 5.960464477539063e-8
-- Testing BinaryCrossEntropyLossLayer on CPUBackend{Float32}...
    > [6,2,4,5]
state.loss - expected_loss => 6.67572021484375e-6
-- Testing BinaryCrossEntropyLossLayer on CPUBackend{Float32}...
    > [3,3,4,5,6]
state.loss - expected_loss => 1.9073486328125e-5
-- Testing BinaryCrossEntropyLossLayer on CPUBackend{Float64}...
    > [7,5]
state.loss - expected_loss => 4.440892098500626e-16
-- Testing BinaryCrossEntropyLossLayer on CPUBackend{Float64}...
    > [5,5,2,3]
state.loss - expected_loss => 5.329070518200751e-15
-- Testing BinaryCrossEntropyLossLayer on CPUBackend{Float64}...
    > [7,4,3,5,2]
state.loss - expected_loss => -7.105427357601002e-14
-- Testing BinaryCrossEntropyLossLayer on GPUBackend{Float32}...
    > [5,2]
state.loss - expected_loss => 0.0
-- Testing BinaryCrossEntropyLossLayer on GPUBackend{Float32}...
    > [4,5,6,5]
state.loss - expected_loss => 9.5367431640625e-6
-- Testing BinaryCrossEntropyLossLayer on GPUBackend{Float32}...
    > [5,4,5,5,6]
state.loss - expected_loss => -1.52587890625e-5
-- Testing BinaryCrossEntropyLossLayer on GPUBackend{Float64}...
    > [2,4]
state.loss - expected_loss => 6.838492938587848e-9
-- Testing BinaryCrossEntropyLossLayer on GPUBackend{Float64}...
    > [5,6,7,2]
state.loss - expected_loss => -5.927588517806726e-7
-- Testing BinaryCrossEntropyLossLayer on GPUBackend{Float64}...
    > [5,7,7,6,4]
state.loss - expected_loss => 6.11990581091959e-5
ERROR: test failed: -eps < state.loss - expected_loss < eps
 in error at error.jl:21 (repeats 2 times)
while loading C:\Users\droidicus\.julia\v0.4\Mocha\test\layers\binary-cross-entropy-loss.jl, in expression starting on line 73
```

**Comment by pluskid** [comment]
Thanks for the details! The latest fixes should hopefully fix this issue.

**Pull request merged**
