### PR TITLE
[WIP] Opencl backend

### PR DESCRIPTION
**Pull request by nstiurca**
Initial stubs for having an OpenCL backend. The idea is to be similar to CUDA backend, leveraging [CLBLAS.jl](https://github.com/JuliaGPU/OpenCL.jl) where possible and writing custom kernels otherwise. Nothing is implemented yet, but renamed `GPUBackend` -> `CUDABackend`, and added `OpenCLBackend <: AbstractGPUBackend`. Also stubbed out `ClTensorBlob` and testing. One thing that is implemented so far is detecting the environment variables dealing with enabling OpenCL.

### CODE REVIEW

**Comment by vchuravy** [comment]
@nstiurca I am one of the maintainers of `OpenCL.jl` let me know if I can do anything to make your life easier.

**Comment by nstiurca** [comment]
@vchuravy Thanks. The only hiccup I've had so far is that I had to checkout master instead of the tag that Julia package manager pulls by default. I imagine these sorts of things will be updated across a whole slew of packages now that we finally have the 0.4 release.

**Comment by pluskid** [comment]
Great! :+1:

**Comment by nstiurca** [comment]
@vchuravy I ran into two small issues with OpenCL. I whipped up some pull requests.

**Comment by nstiurca** [comment]
This has completely fallen off my radar and I don't foresee working on this again any time soon. Besides, I'm sure much has changed in the past couple of years, so closing.

**Pull request closed without merging**
