### PR TITLE
Idea for how to deal with RNN

### PR DESCRIPTION
**Pull request by RatanRSur**
The thought was that a layer would be specified as recurrent on instantiation and there would be a check for the existence of any recurrence in the net by net.jl. Based on the return value of this check, either the traditional topological functions would be called or a special recurrent one would, which would take into account time steps when creating the net.

P.S. The issue with the previous pull request was that I selected `dev` which had a lot of other commits or something. This one is based at master, which doesn't make sense, it should have it's own branch, (like RNN) but at least this allows for viewing of the commits without all the extraneous stuff.

### CODE REVIEW

**Comment by RatanRSur** [comment]
Any thoughts on this?

**Comment by pluskid** [comment]
Yes I agree with your concerns about branching. That's actually how it works, I have been using master branch for development for a while and I will have my local branch. I only push to the master branch from my local branch while the component is finished, to keep the master in a consistent state. The same convention should work here. I will not merge this pr until something relatively finished is done, and that allows you the most flexibility because you are working with your own branch. And this thread should be good for discussings along development.

**Comment by RatanRSur** [comment]
Oh no, of course I don't actually think this should be merged haha, it's just two small changes that don't do anything. What I wanted was some feedback on my idea for how to go about it. Specifically, using a different function in net.jl for the "creation" of the net when a recurrent layer is present. The main problem I see with this is that it uses a lot of space, as a higher time step input results in a longer net. Does a different approach come to mind?

**Comment by pluskid** [comment]
@RatanRSur Yes, the recurrent net might take quite a lot of space (linear in time steps). I think if one only need to do forward computation, the space could definitely be saved by iteratively re-use the data blobs in each time step and only keep history of the previous step. But to do backward computation, one actually need to keep the results of the forward phase to compute some gradient, so it seems somewhat difficult to avoid those data overhead. But I'm not very clear about clever RNN implementation methods, maybe you may look at how other typical recurrent nets are implemented?

**Comment by zahachtah** [comment]
Very interested in how RNN for Mocha is doing. any news on this?

**Comment by RatanRSur** [comment]
I haven't continued work on this for a few reasons:

1. I got distracted by other things :stuck_out_tongue:
2. When I looked over the codebase, I had an ok understanding of it but not one that I felt was good enough to deal with the uniqueness of RNN's. 

If I were to continue work on it, these would probably be my next steps:

1. Understand how Caffe made efficiently represents them https://github.com/BVLC/caffe/pull/2033
2. Find out to what extent that's applicable here

I could see this as something I would definitely want to help with in the future but can't contribute the time at the moment.

**Pull request closed without merging**
