### PR TITLE
Adding windows DLLs for cudNN 3, CUDA 6.5, and 32-bit versions of each

### PR DESCRIPTION
**Pull request by droidicus**
Add support for cudNN on Windows, add 32-bit dll names, change eps for Float64 convolution layer to match, and compatibility fix in channel-pooling.

### CODE REVIEW

**Comment by droidicus** [comment]
Resolve #109

**Comment by pluskid** [comment]
@droidicus Thanks very much! Why did you change `Compat.unsafe_convert` to `convert`. Did you run into issue with `Compat.unsafe_convert`? I asked this because this change was just merged from PR #108

**Comment by droidicus** [comment]
I am not sure why, but it was causing problems with the tests (the channel-pooling tests were taking over an order of magnitude longer in GPU then in CPU) , still looking into it. At this point I think there may be an issue in the Compat package. Right now Julia 0.3 works fine from what I can see, but 0.4 is still throwing a bunch of warnings about `convert(::Type{Ptr}, ...)`

**Comment by pluskid** [comment]
@droidicus OK, I'm going to merge this PR, but also open an issue about this. Thanks!

**Pull request merged**
