### PR TITLE
Leaky ReLU

### PR DESCRIPTION
**Pull request by stjanovitz**

### CODE REVIEW

**Comment by pluskid** [comment]
Thanks! Why the leaky parameter fixed as 0.01? Shall we make it configurable or even learnable?

**Comment by stjanovitz** [comment]
[This paper](https://web.stanford.edu/~awni/papers/relu_hybrid_icml2013_final.pdf) was able to get slightly faster convergence on its network with the parameter fixed at 0.01, but it would be great to make the parameter learnable since [this paper](http://arxiv.org/pdf/1502.01852v1.pdf) improved its network's accuracy by doing so.

**Comment by pluskid** [comment]
@stjanovitz Thanks very much for the contribution! Making it learnable needs a little bit extra work, but making it a customizable (but fixed, non-learnable) parameter is much easier. Are you planning to do that? If you are, I will wait for that before merging this pull-request. If not, that's fine. Just let me know, I will merge this PR right away and I will try to modify that later when I find some time.

Thanks again!

**Comment by stjanovitz** [comment]
I wasn't planning on doing that, but feel free to modify it.

**Pull request merged**
