### PR TITLE
Attempted update to 0.7/1.0 - May need more work given segfault

### PR DESCRIPTION
**Pull request by ianshmean**
I think I've covered the basic updates to 1.0 syntax and this now now loads in 1.0.2 and 1.1.0-dev

However, the only example I've run  (examples/ijulia/ilsvrc12/imagenet-classifier.ipynb) segfaults at the `net = Net("imagenet", backend, layers)` line.

### CODE REVIEW

**Comment by pluskid** [comment]
@ianshmean Thanks very much for the efforts!! I will try to see what is seg-faulting. 

Meanwhile, there seem to be a pre-generated UUID for every existing old package. For example, the one for Mocha.jl is [here](https://github.com/JuliaRegistries/General/blob/master/M/Mocha/Package.toml). The UUID seem to be different to the one in your PR. How did you generate the UUID in your PR? 

Also, I'm new to the new Package management system, my guess is that the file `Manifest.toml` should not be part of a package?

**Comment by ianshmean** [comment]
Happy to help!

I've updated the UUID to match, and as for the `Manifest.toml` file, from what I can tell both it and `Project.toml` can be checked in, according to [this](https://docs.julialang.org/en/v1/stdlib/Pkg/index.html) but it is hard to find example projects out there that are fully converted

**Comment by ianshmean** [comment]
@pluskid I've been trying to figure out the segfault but failed so far. Have you found any clues? (I'm eager to incorporate Mocha into some v1.0 code)

**Comment by pluskid** [comment]
Still pushing through compatibility issues and modifying things on top of your commits. I'm trying to work it out from the unit tests, which I think is potentially easier to debug than the notebook.

**Comment by ianshmean** [comment]
By the way, my MacOS Mojave setup was missing GraphViz for the `dot` functions, so that might need to added to build. I've been trying to figure that out, but the standard `Homebrew.jl` installation example seems to not work (once you've corrected for 1.0 syntax)

**Comment by pluskid** [comment]
The segfault is mysteriously caused by the logging library memento.jl. I have temporarily disabled it. The fixes for unit tests now should work on CPU, but there should still be a lot of work to be done on GPU. Hope I can fix those over the weekend.

I created a new PR that contains your commits to track the progress #255

**Pull request closed without merging**
